//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchSetting
    {
        public long Recno { get; set; }
        public string BranchCode { get; set; }
        public string Name { get; set; }
        public string Photos_Path { get; set; }
        public string ReferenceNumberPrefix1 { get; set; }
        public string ReferenceNumberPrefix2 { get; set; }
        public string TreasuryAccountNo { get; set; }
        public string StampDutyGlAccount { get; set; }
        public string Excise_Duty_GlAccount { get; set; }
        public string MembersChequeSuspense_GlAccount { get; set; }
        public string pettyCashAccount { get; set; }
        public string WithholdingtaxAccount { get; set; }
        public string backup_Path { get; set; }
        public string MemNo_From { get; set; }
        public string MemNo_to { get; set; }
        public System.Guid BranchSettingsId { get; set; }
    }
}
