//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long Recno { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyTelephone { get; set; }
        public string CompanyPin { get; set; }
        public string AccountPicture { get; set; }
        public Nullable<decimal> SavingsMinimumBalance { get; set; }
        public string GLAccountPicture { get; set; }
        public string MembershipNumberPicture { get; set; }
        public Nullable<decimal> CashDepositAuthorityAmount { get; set; }
        public Nullable<decimal> CashWithdrawalAuthorityAmount { get; set; }
        public Nullable<decimal> ChequeDepositAuthorityAmount { get; set; }
        public Nullable<decimal> CashReceiptsAuthorityAmount { get; set; }
        public Nullable<decimal> CashPaymentsAuthorityAmount { get; set; }
        public Nullable<decimal> Excise_Duty_Rate { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public Nullable<decimal> DormancyPeriod { get; set; }
        public Nullable<decimal> noticedays { get; set; }
        public Nullable<bool> ChqDeposit_Commission_Charge_On_Deposit { get; set; }
        public Nullable<decimal> TellerCashInsuranceLimit { get; set; }
        public Nullable<bool> SummariseLedgerPostings { get; set; }
        public Nullable<decimal> WithholdingtaxRate { get; set; }
        public string WithholdingtaxAccount { get; set; }
        public Nullable<bool> Capture_Guarantors_during_Appraisal { get; set; }
        public Nullable<decimal> OrdinaryChequeCommission { get; set; }
        public string OrdinaryCheque_account { get; set; }
        public Nullable<decimal> BankersChequeCommission_Sacco { get; set; }
        public Nullable<decimal> BankersChequeCommission_Bank { get; set; }
        public string BankersCheque_account { get; set; }
        public string DisplayMessage { get; set; }
        public string AtmCard_BinNumber { get; set; }
        public string atmSettlementAccount { get; set; }
        public string atmLinkChargeAccount { get; set; }
        public Nullable<decimal> atmLinkChargeCoop { get; set; }
        public Nullable<decimal> atmLinkChargeSacco { get; set; }
        public string Surplus_Loss_Account { get; set; }
        public Nullable<decimal> atmPinChange_Charge { get; set; }
        public string CoopSocietyNo { get; set; }
        public Nullable<decimal> teller_commission_split_percentage { get; set; }
        public Nullable<bool> Teller_CloseDay_Transfer_Cash_to_Treasury { get; set; }
        public Nullable<int> Maximum_Guaranteeship { get; set; }
        public string Teller_Slip_FooterText { get; set; }
        public Nullable<int> System_Lock_Out_time { get; set; }
        public string Bod_stdorder_RecoveryCode { get; set; }
        public string SupplierWithholdingtaxAccount { get; set; }
        public string Deceased_FuneralRider_AccountNo { get; set; }
        public string Deceased_LoanInsurance_AccountNo { get; set; }
        public string SinkingFundCode { get; set; }
        public Nullable<decimal> RetirementBonus { get; set; }
        public string RetirementBonus_AccountNo { get; set; }
        public Nullable<decimal> RetirementBonus_commission { get; set; }
        public string RetirementBonus_comm_AccountNo { get; set; }
        public Nullable<decimal> SaccoLink_Extra_Sacco_Charges { get; set; }
        public string SaccoLink_Extra_Sacco_Charges_Ac { get; set; }
        public string SaccoLink_Atm_ChargesAccount { get; set; }
        public string SaccoLink_Pos_SettlementAccount { get; set; }
        public string SaccoLink_Pos_ChargesAccount { get; set; }
        public Nullable<bool> Capture_Manual_LoanNumber { get; set; }
        public Nullable<decimal> CBK_CUSTOMER_CASH_WD_DEP_LIMIT { get; set; }
        public Nullable<decimal> DailyAtmWithdrawal_Limit { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<int> Teller_Print_Copies { get; set; }
    }
}
