//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Deceased
    {
        public long recno { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string SoureDocid { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime DateReported { get; set; }
        public string PlacedBy { get; set; }
        public Nullable<System.DateTime> DateDeceased { get; set; }
        public string ReportedBy { get; set; }
        public string ReportedBy_Phone { get; set; }
        public System.Guid tbl_DeceasedID { get; set; }
    }
}
