//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Web_ProductRepayments
    {
        public System.Guid TransactionId { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long RowId { get; set; }
    }
}
