//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoanInsuranceRates
    {
        public long recno { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<decimal> InsuranceRate { get; set; }
        public Nullable<decimal> Constance { get; set; }
    }
}
