//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StdOrderTypes
    {
        public long Recno { get; set; }
        public string OrderType { get; set; }
        public string OrderDescription { get; set; }
        public Nullable<bool> NotApplicable { get; set; }
        public System.Guid tbl_StdOrderTypesID { get; set; }
    }
}
