//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvestmentCodes
    {
        public long recno { get; set; }
        public string InvestmentCode { get; set; }
        public string InvestmentName { get; set; }
        public string PrincipalAccount { get; set; }
        public Nullable<decimal> monthlyrate { get; set; }
        public Nullable<decimal> MaximumBalance { get; set; }
        public string CheckOff_MatchCode { get; set; }
        public Nullable<bool> Refundable_on_Cessation { get; set; }
        public string Dividend_Desc { get; set; }
        public Nullable<decimal> Minimum_Monthly_Contribution { get; set; }
        public System.Guid tbl_InvestmentCodesID { get; set; }
        public string Dividend_Expense_Account { get; set; }
        public string Dividend_Payable_Account { get; set; }
    }
}
