//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GuarantorsAttachDetails
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReference { get; set; }
        public string CustomerNo { get; set; }
        public string ProductType { get; set; }
        public string GuarantorNo { get; set; }
        public string LoanType { get; set; }
        public decimal AmountIssued { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal RepaymentAmount { get; set; }
        public decimal PrincipalAmount { get; set; }
        public decimal Interest { get; set; }
        public decimal ByProductAmount { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public string CapturedBy { get; set; }
        public System.Guid tbl_GuarantorsAttachDetailsID { get; set; }
    }
}
