//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MicroAgent
    {
        public long Recno { get; set; }
        public string Agentcode { get; set; }
        public string AgentName { get; set; }
        public string Telephone { get; set; }
        public System.Guid Tbl_MicroAgentID { get; set; }
    }
}
