//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CheckOff_LinkCodes
    {
        public long RECNO { get; set; }
        public string ProductCode { get; set; }
        public string CheckoffCode { get; set; }
        public Nullable<decimal> MaximumAmount { get; set; }
        public System.Guid tbl_CheckOff_LinkCodesID { get; set; }
    }
}
