//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerAccounts
    {
        public long recno { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime OpenedDate { get; set; }
        public string OpenedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public string AuthorisedBy { get; set; }
        public bool Locked { get; set; }
        public string AccountRemarks { get; set; }
        public string AccountComments { get; set; }
        public decimal AccountType { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string ClosedBy { get; set; }
        public System.Guid tbl_CustomerAccountsID { get; set; }
    }
}
