//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaccoLink_Atm8585ISOFields
    {
        public decimal ISOFieldID { get; set; }
        public string ISOFieldFormat { get; set; }
        public string Description { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
