//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LinkProcess
    {
        public long recno { get; set; }
        public string AccountNo { get; set; }
        public string CardNumber { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Enabled { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string LoginId { get; set; }
        public string Narration { get; set; }
        public string DOCID { get; set; }
    }
}
