//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanDisbursementDays
    {
        public long recno { get; set; }
        public string LoanCode { get; set; }
        public decimal From_Amount { get; set; }
        public decimal TO_Amount { get; set; }
        public int Days_Before_Disbursmenent { get; set; }
        public System.Guid tbl_LoanDisbursementDaysID { get; set; }
    }
}
