//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LnRegister
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string ReferenceNo { get; set; }
        public string CustomerNo { get; set; }
        public string ProductCode { get; set; }
        public string PurposeCode { get; set; }
        public decimal AmountApplied { get; set; }
        public decimal RepaymentPeriod { get; set; }
        public decimal ProcessingLevel { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string RegisteredBranch { get; set; }
        public string ShareCode { get; set; }
        public decimal ShareBalance { get; set; }
        public decimal LoanBalance { get; set; }
        public string FormSerialNumber { get; set; }
        public Nullable<decimal> MaximumEntitlement { get; set; }
        public Nullable<decimal> SharesFactor { get; set; }
        public Nullable<decimal> Os_Balances { get; set; }
        public Nullable<decimal> totalClearance { get; set; }
        public Nullable<decimal> Entitled { get; set; }
        public Nullable<decimal> AppraisalMtd { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<decimal> TotalAdditions { get; set; }
        public Nullable<decimal> TotalSubstractions { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> MaximumLoanAbility { get; set; }
        public string LoanReductionReason { get; set; }
        public Nullable<decimal> Sys_Recommend { get; set; }
        public Nullable<System.DateTime> AppraisalDate { get; set; }
        public string AppraisedBy { get; set; }
        public string AppraisedBranch { get; set; }
        public Nullable<decimal> AppraisedAmount { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalBy { get; set; }
        public string ApprovalBranch { get; set; }
        public Nullable<decimal> ApprovalAmount { get; set; }
        public string ApprovalBatch { get; set; }
        public string AudittedBy { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditBranch { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string PostedBranch { get; set; }
        public string RecoveryCode { get; set; }
        public string Savings_AccountNo { get; set; }
        public Nullable<decimal> Checkoff_Deduction_Amount { get; set; }
        public System.Guid tbl_LnRegisterID { get; set; }
        public string LoanOfficer { get; set; }
    }
}
