//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostingHeader
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReference { get; set; }
        public string PostingDescription { get; set; }
        public string PostingType { get; set; }
        public decimal PostingTotal { get; set; }
        public string PostingCommission { get; set; }
        public string LedgerAccount { get; set; }
        public string CreatedBy { get; set; }
        public string CreateBranch { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ReferenceDate { get; set; }
        public string OrderType { get; set; }
        public bool RecoverStandingOrders { get; set; }
        public string PayoutCode { get; set; }
        public string LinkCode { get; set; }
        public string BatchedBy { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string OtherCommission { get; set; }
        public string Previous_Checkoff_Reference { get; set; }
        public System.Guid tbl_PostingHeaderID { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    }
}
