//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cheque_types
    {
        public long RECNO { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ChargeCode { get; set; }
        public Nullable<int> Days { get; set; }
        public System.Guid tbl_cheque_typesID { get; set; }
    }
}
