//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Authorisations
    {
        public long recno { get; set; }
        public string AccountNo { get; set; }
        public string Docid { get; set; }
        public string Narration { get; set; }
        public decimal TransactionAmount { get; set; }
        public string SourceUser { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string SourceBranch { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string DestinationUserCode { get; set; }
        public System.Guid tbl_AuthorisationsID { get; set; }
    }
}
