//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanGuarantors_History
    {
        public long Recno { get; set; }
        public string CustomerNo { get; set; }
        public string GuarantorNo { get; set; }
        public string GuarantorIdNo { get; set; }
        public string PostingDocid { get; set; }
        public string ReferenceNo { get; set; }
        public decimal GuaranteedAmount { get; set; }
        public decimal GuarantorBalance { get; set; }
        public string GuarantorShareType { get; set; }
        public string LoanType { get; set; }
    }
}
