//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerNextofKin
    {
        public long Recno { get; set; }
        public string CustomerNo { get; set; }
        public string KinName { get; set; }
        public string KinIdNumber { get; set; }
        public string KinPhoneNumber { get; set; }
        public string KinRelation { get; set; }
        public System.Guid tbl_customerNextofKinID { get; set; }
    }
}
