//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GlBudget
    {
        public long Recno { get; set; }
        public decimal FinancialYear { get; set; }
        public string BranchCode { get; set; }
        public string GlAccountNo { get; set; }
        public decimal BudgetAmount { get; set; }
        public System.Guid tbl_glbudgetID { get; set; }
    }
}
