//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanDisburseCharges
    {
        public long recno { get; set; }
        public string LoanCode { get; set; }
        public string ChargeCode { get; set; }
        public bool Upfront { get; set; }
        public string Section { get; set; }
        public System.Guid tbl_LoanDisburseChargesID { get; set; }
    }
}
