//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GlTransactionCodes
    {
        public long recno { get; set; }
        public string desc_ { get; set; }
        public string Other { get; set; }
        public string Type { get; set; }
        public System.Guid tbl_GlTransactionCodesID { get; set; }
    }
}
