//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChequeBooks
    {
        public long RECNO { get; set; }
        public string ChequeType { get; set; }
        public string GlAccountNo { get; set; }
        public int StartingLeaf { get; set; }
        public int EndingLeaf { get; set; }
        public System.DateTime DateIssued { get; set; }
        public string IssuedBy { get; set; }
        public string DestinationBranch { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public System.Guid tbl_ChequeBooksID { get; set; }
    }
}
