//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanVariations
    {
        public long Recno { get; set; }
        public string CustomerNo { get; set; }
        public string ProductCode { get; set; }
        public string RefAccount { get; set; }
        public decimal NewAmnt { get; set; }
        public decimal CurrentAmnt { get; set; }
        public decimal NewBal { get; set; }
        public decimal CurrBal { get; set; }
        public int TransType { get; set; }
        public string TransName { get; set; }
        public int Interest { get; set; }
        public int Action { get; set; }
        public decimal Ability { get; set; }
        public System.DateTime ByProductMonth { get; set; }
        public string EmployerCode { get; set; }
    }
}
