//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bod_Allowances
    {
        public long recno { get; set; }
        public string AllowanceCode { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<bool> DeductPaye { get; set; }
        public string GlAccountNo { get; set; }
        public string TaxGlAccountNo { get; set; }
        public string SummaryColumn_Name { get; set; }
        public System.Guid tbl_Bod_AllowancesID { get; set; }
    }
}
