//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerAuthorised
    {
        public long Recno { get; set; }
        public string CustomerNo { get; set; }
        public string AuthorisedName { get; set; }
        public string AuthorisedIdNumber { get; set; }
        public string AuthorisedPhoneNumber { get; set; }
        public string AuthorisedInstructions { get; set; }
        public System.Guid tbl_customerAuthorisedID { get; set; }
    }
}
