//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Paycommissions
    {
        public long recno { get; set; }
        public string code { get; set; }
        public string desc_ { get; set; }
        public Nullable<decimal> from_ { get; set; }
        public Nullable<decimal> to_ { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> ACCTYPE { get; set; }
        public System.Guid tbl_PaycommissionsID { get; set; }
    }
}
