//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Suspense_Account_Transactions
    {
        public long Recno { get; set; }
        public string Source_Account { get; set; }
        public string Source_Docid { get; set; }
        public string Source_Reference { get; set; }
        public string Source_Narration { get; set; }
        public decimal Source_Amount { get; set; }
        public string Destination_Account { get; set; }
        public System.DateTime TransferDate { get; set; }
    }
}
