//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoanEarningDedUctionCodes
    {
        public long recno { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Type { get; set; }
        public System.Guid rowguid { get; set; }
        public System.Guid Tbl_LoanEarningDedUctionCodesID { get; set; }
    }
}
