//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentTypes
    {
        public long Recno { get; set; }
        public string Paycode { get; set; }
        public string PaymentDescription { get; set; }
        public string PayGlAccount { get; set; }
        public Nullable<bool> ChargeExciseDuty { get; set; }
        public System.Guid tbl_PaymentTypesID { get; set; }
    }
}
