//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bod_Titles
    {
        public long RECNO { get; set; }
        public string PostCode { get; set; }
        public string PostName { get; set; }
        public System.Guid tbl_Bod_TitlesID { get; set; }
    }
}
