//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReferenceNumbers
    {
        public long Recno { get; set; }
        public string Docid { get; set; }
        public string ReferenceNumber { get; set; }
        public string BranchCode { get; set; }
    }
}
