//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StatementPrinting_History
    {
        public long recno { get; set; }
        public string CustomerNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public bool Charged { get; set; }
        public string UserId { get; set; }
        public string machine { get; set; }
        public string SourceBranch { get; set; }
        public string Reptype { get; set; }
    }
}
