//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FixedRates
    {
        public long recno { get; set; }
        public Nullable<decimal> fromamount { get; set; }
        public Nullable<decimal> toAmount { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public System.Guid tbl_FixedRatesID { get; set; }
    }
}
