//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChequeBooks_Used
    {
        public long RECNO { get; set; }
        public string ChequeType { get; set; }
        public string GlAccountNo { get; set; }
        public int Leaf { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string UserCode { get; set; }
        public string PostingDocid { get; set; }
        public string ReferenceNo { get; set; }
        public decimal TransactionAmount { get; set; }
        public string BranchCode { get; set; }
        public string PayeeName { get; set; }
        public string Source_Account { get; set; }
    }
}
