//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostingDetails_CheckOff
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReference { get; set; }
        public string ReferenceNo { get; set; }
        public string ReferenceName { get; set; }
        public string Product { get; set; }
        public string Narration { get; set; }
        public decimal CreditAmount { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal Balance { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public string CapturedBy { get; set; }
        public System.Guid tbl_PostingDetails_CheckOffID { get; set; }
    }
}
