//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostingDividends_Rates
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReference { get; set; }
        public string ProductCode { get; set; }
        public decimal Rate { get; set; }
        public decimal WtaxRate { get; set; }
        public string PayableGlAccount { get; set; }
        public System.Guid tbl_PostingDividends_RatesID { get; set; }
    }
}
