//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CheckOffFile_ExtractColumn
    {
        public System.Guid tbl_CheckOffFile_ExtractColumnId { get; set; }
        public System.Guid tbl_Checkoff_FileId { get; set; }
        public string FileColumn { get; set; }
        public string FieldName { get; set; }
        public int StartPos { get; set; }
        public int ColumnLength { get; set; }
    }
}
