//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sharesDrive
    {
        public long recno { get; set; }
        public string CustomerNo { get; set; }
        public string ProductCode { get; set; }
        public string PostingDocid { get; set; }
        public string ReferenceNo { get; set; }
        public decimal CreditAmount { get; set; }
        public string FormNumber { get; set; }
        public string RecruitedBy { get; set; }
        public System.DateTime DateCaptured { get; set; }
        public string BranchCode { get; set; }
        public string CapturedBy { get; set; }
    }
}
