//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductArrears
    {
        public long recno { get; set; }
        public string Source_CustomerNo { get; set; }
        public string SourceAccountNo { get; set; }
        public string Beneficiary_CustomerNo { get; set; }
        public string DestinationAccountNo { get; set; }
        public decimal DebitAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int ProductSection { get; set; }
        public decimal CreditAmount { get; set; }
        public string Narration { get; set; }
        public string LoginCode { get; set; }
        public System.Guid tbl_ProductArrearsID { get; set; }
    }
}
