//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public long Recno { get; set; }
        public string LoginCode { get; set; }
        public string LoginName { get; set; }
        public string FullName { get; set; }
        public string EmailID { get; set; }
        public string UserBranch { get; set; }
        public string LoginTime_From { get; set; }
        public string LoginTime_To { get; set; }
        public string LoginMachine { get; set; }
        public string LoginPassword { get; set; }
        public bool AccountDisabled { get; set; }
        public string AccessRights { get; set; }
        public Nullable<decimal> TellerAuthorisationLimit { get; set; }
        public Nullable<System.DateTime> PasswordExpiry { get; set; }
        public Nullable<System.DateTime> Login_Expiry { get; set; }
        public Nullable<decimal> LoanApprovalLimit { get; set; }
        public Nullable<decimal> LoanDisbursementLimit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserRole { get; set; }
        public string Teller_Excess_GlAccount { get; set; }
        public string Teller_Shortage_GlAccount { get; set; }
        public string EmploymentNumber { get; set; }
        public string SaccoMembershipNumber { get; set; }
        public Nullable<decimal> CashWithdrawalAlertAmount { get; set; }
        public string OtherUserRoles { get; set; }
        public System.Guid tbl_usersID { get; set; }
        public string WebPassword { get; set; }
    }
}
