//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reco_CashBook
    {
        public long Recno { get; set; }
        public string GlAccountNo { get; set; }
        public string GlContra { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Narration { get; set; }
        public string Docid { get; set; }
        public string ReferenceNo { get; set; }
        public string LoginCode { get; set; }
        public string Machine { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime AuditTime { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
        public System.Guid Ledger_RowGuid { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ImportedPeriod { get; set; }
        public string ImportedBy { get; set; }
        public System.DateTime ImportedDate { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public string ReconciledBy { get; set; }
        public Nullable<System.DateTime> ReconciliationPeriod { get; set; }
    }
}
