//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accounttypes
    {
        public long recno { get; set; }
        public Nullable<decimal> code { get; set; }
        public string act_code { get; set; }
        public string category { get; set; }
        public string glmemsav { get; set; }
        public Nullable<decimal> minimum_bal { get; set; }
        public Nullable<decimal> earningbalance { get; set; }
        public string cashDepositComm_Code { get; set; }
        public Nullable<decimal> premature_days { get; set; }
        public string prem_code { get; set; }
        public Nullable<decimal> notice_days { get; set; }
        public string noticecode { get; set; }
        public Nullable<decimal> notice_amount { get; set; }
        public string withcomm_code { get; set; }
        public Nullable<decimal> interestrate { get; set; }
        public string Encashment_code { get; set; }
        public string StatementChargeCode { get; set; }
        public string Cheque_Comm_AcHolders { get; set; }
        public string Cheque_Comm_Non_AcHolders { get; set; }
        public string Interest_payable_Account { get; set; }
        public string Interest_expense_Account { get; set; }
        public string Entrance_fee { get; set; }
        public string AccountOpening_code { get; set; }
        public Nullable<bool> Disallow_Teller_Transactions { get; set; }
        public Nullable<bool> Recover_sorder_To_Zero { get; set; }
        public string Complete_Withdrawal_charge_code { get; set; }
        public System.Guid tbl_accounttypesID { get; set; }
    }
}
