//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostingLinkCodes
    {
        public string LinkCode { get; set; }
        public string MatchBy { get; set; }
        public Nullable<int> Length { get; set; }
        public System.Guid tbl_PostingLinkCodesID { get; set; }
    }
}
