//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Teller_Closing
    {
        public long Recno { get; set; }
        public string TellerAccount { get; set; }
        public string LoginCode { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal Deposits { get; set; }
        public decimal Withdrawals { get; set; }
        public decimal ClosingBalance { get; set; }
        public decimal Excess { get; set; }
        public decimal Shortage { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Source_Br { get; set; }
        public string PostingReference { get; set; }
        public string PostingDocid { get; set; }
        public Nullable<decimal> n1000 { get; set; }
        public Nullable<decimal> n500 { get; set; }
        public Nullable<decimal> n200 { get; set; }
        public Nullable<decimal> n100 { get; set; }
        public Nullable<decimal> n50 { get; set; }
        public Nullable<decimal> n40 { get; set; }
        public Nullable<decimal> n20 { get; set; }
        public Nullable<decimal> n10 { get; set; }
        public Nullable<decimal> n5 { get; set; }
        public Nullable<decimal> n1 { get; set; }
        public Nullable<decimal> n050 { get; set; }
        public Nullable<decimal> n010 { get; set; }
        public Nullable<decimal> n005 { get; set; }
        public Nullable<decimal> mm005 { get; set; }
        public Nullable<decimal> mm010 { get; set; }
        public Nullable<decimal> mm050 { get; set; }
        public Nullable<decimal> mm1 { get; set; }
        public Nullable<decimal> mm5 { get; set; }
        public Nullable<decimal> mm10 { get; set; }
        public Nullable<decimal> mm20 { get; set; }
        public Nullable<decimal> mm40 { get; set; }
        public Nullable<decimal> mm50 { get; set; }
        public Nullable<decimal> mm100 { get; set; }
        public Nullable<decimal> mm200 { get; set; }
        public Nullable<decimal> mm500 { get; set; }
        public Nullable<decimal> mm1000 { get; set; }
    }
}
