//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bod_Allowance_Rates
    {
        public long recno { get; set; }
        public string CommiteeCode { get; set; }
        public string AllowanceCode { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Taxation_Rate { get; set; }
        public System.Guid tbl_Bod_Allowance_RatesID { get; set; }
    }
}
