//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notice
    {
        public long recno { get; set; }
        public string AccountNo { get; set; }
        public string SoureDocid { get; set; }
        public string SourceReferenceNumber { get; set; }
        public System.DateTime NoticeDate { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public string PlacedBy { get; set; }
        public Nullable<System.DateTime> WithDrawalDate { get; set; }
        public string Docid { get; set; }
        public string ReferenceNo { get; set; }
        public System.Guid tbl_NoticeID { get; set; }
    }
}
