//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StandingOrderRecoveryPriority
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string act_code { get; set; }
        public string RecoveryPriority { get; set; }
        public System.Guid tbl_StandingOrderRecoveryPriorityID { get; set; }
    }
}
