//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trail
    {
        public long recno { get; set; }
        public string LoginCode { get; set; }
        public string Activity { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string MachineName { get; set; }
        public Nullable<decimal> TrAmount { get; set; }
        public string AccountNo { get; set; }
        public string PostingDocid { get; set; }
        public System.DateTime MachineDate { get; set; }
        public System.Guid tbl_trailID { get; set; }
    }
}
