//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bod_commitee_members
    {
        public long recno { get; set; }
        public string CustomerNo { get; set; }
        public string CommitteeCode { get; set; }
        public string TitleCode { get; set; }
        public System.DateTime DateLinked { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateDelinked { get; set; }
        public System.Guid tbl_Bod_commitee_membersID { get; set; }
    }
}
