//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ledger_Classiffication
    {
        public long recno { get; set; }
        public string CODE { get; set; }
        public string FROM_ACCOUNT { get; set; }
        public string TO_ACCOUNT { get; set; }
    }
}
