//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GlSubCategory
    {
        public long Recno { get; set; }
        public string ClassCode { get; set; }
        public string SubCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.Guid tbl_glsubcategoryID { get; set; }
    }
}
