//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostingDividends_Details
    {
        public long recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReference { get; set; }
        public Nullable<decimal> paid { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public decimal ShareBalance { get; set; }
        public decimal ShareAmount { get; set; }
        public decimal ShareWithholdingtaxAmount { get; set; }
        public decimal CapitalBalance { get; set; }
        public decimal CapitalAmount { get; set; }
        public decimal CapitalWithholdingtaxAmount { get; set; }
        public decimal NetDividend { get; set; }
    }
}
