//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_withdrawalNotices
    {
        public long RECNO { get; set; }
        public string CustomerNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public string ReasonForWithdrawal { get; set; }
        public System.Guid tbl_withdrawalNoticesId { get; set; }
    }
}
