//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Departments
    {
        public long Recno { get; set; }
        public string DptCode { get; set; }
        public string DptName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> SavingsMinimumBalance { get; set; }
        public Nullable<bool> Block_Employer { get; set; }
        public System.Guid tbl_DepartmentsID { get; set; }
    }
}
