//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_appraisalTypes
    {
        public long recno { get; set; }
        public string AppraisalCode { get; set; }
        public string AppraisalName { get; set; }
        public string RecoveryModule { get; set; }
        public string AppraisalMode { get; set; }
        public System.Guid tbl_appraisalTypesID { get; set; }
    }
}
