//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaccolInk_Transactions
    {
        public string AccountID { get; set; }
        public string SystemTrace { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string UniqueTrxID { get; set; }
        public string TrxType { get; set; }
        public string Narration { get; set; }
        public string ATMMachineNo { get; set; }
        public string ATMCardNo { get; set; }
        public Nullable<int> ReversalId { get; set; }
        public string InMessage { get; set; }
        public long Recno { get; set; }
    }
}
