//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reco_BnkStatement
    {
        public long Recno { get; set; }
        public string GlAccountNo { get; set; }
        public System.DateTime StatementDate { get; set; }
        public System.DateTime ValueDate { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Narration { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ImportedPeriod { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
        public string CapturedBy { get; set; }
        public System.DateTime CapturedDate { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public string ReconciledBy { get; set; }
        public Nullable<System.DateTime> ReconciliationPeriod { get; set; }
        public Nullable<decimal> Cashbook_DebitAmount { get; set; }
        public Nullable<decimal> Cashbook_CreditAmount { get; set; }
    }
}
