//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanAdvanceCodes
    {
        public string AdvanceCode { get; set; }
        public string LoanAdvanceCode { get; set; }
        public System.Guid Tbl_loanadvancecodesID { get; set; }
    }
}
