//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LongRunningProcesses
    {
        public string PostingId { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReferenceNo { get; set; }
        public System.DateTime PostDate { get; set; }
        public string PostBy { get; set; }
        public string PostAddress { get; set; }
    }
}
