//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CheckOff_ExtractType
    {
        public System.Guid tbl_CheckOff_ExtractTypeId { get; set; }
        public string code { get; set; }
        public string Description { get; set; }
        public string HeaderDescription { get; set; }
        public string FileType { get; set; }
        public Nullable<bool> FixedWidth { get; set; }
        public string Delimiter { get; set; }
    }
}
