//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mpesa_Deposits
    {
        public long Recno { get; set; }
        public string PostingDocid { get; set; }
        public string PostingReferenceNo { get; set; }
        public string ReferenceNo { get; set; }
        public string MobileNo { get; set; }
        public string SenderDetails { get; set; }
        public decimal Amount { get; set; }
        public string Trx_DateTime { get; set; }
        public string Account { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public string ResponseCode { get; set; }
    }
}
