//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SpecialStaff_Committee_Loan_Rates
    {
        public string LoanCode { get; set; }
        public decimal Employer_Paid_Rate { get; set; }
        public string GlAccountNo { get; set; }
    }
}
