//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CustomerAccounts_Extended
    {
        public long recno { get; set; }
        public string AccountNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthCertificateNumber { get; set; }
        public Nullable<int> gender { get; set; }
        public System.Guid Tbl_CustomerAccounts_ExtendedID { get; set; }
    }
}
