//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MicroRegion
    {
        public long Recno { get; set; }
        public string Regioncode { get; set; }
        public string RegionName { get; set; }
        public string AgentNo { get; set; }
        public System.Guid Tbl_MicroRegionID { get; set; }
    }
}
