//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MicroCustomer
    {
        public long Recno { get; set; }
        public string GroupAcc { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.DateTime> Datejoined { get; set; }
        public string LinkedBy { get; set; }
    }
}
