//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Failed_standingOrders
    {
        public long recno { get; set; }
        public string Source_CustomerNo { get; set; }
        public string SourceAccountNo { get; set; }
        public string Beneficiary_CustomerNo { get; set; }
        public string DestinationAccountNo { get; set; }
        public decimal PrincipalAmount { get; set; }
        public decimal InterestAmount { get; set; }
        public System.DateTime DateSet { get; set; }
        public System.DateTime LastRunDate { get; set; }
        public System.DateTime NextRunDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Frequency { get; set; }
        public Nullable<decimal> Period { get; set; }
        public string RecoveryCode { get; set; }
        public Nullable<int> Type { get; set; }
        public string FailureCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
