//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_denoms
    {
        public long recno { get; set; }
        public string Docid { get; set; }
        public string ReferenceNo { get; set; }
        public double X_1000 { get; set; }
        public double X_500 { get; set; }
        public double X_200 { get; set; }
        public double X_100 { get; set; }
        public double X_50 { get; set; }
        public double X_40 { get; set; }
        public double X_20 { get; set; }
        public double X_10 { get; set; }
        public double X_5 { get; set; }
        public double X_1 { get; set; }
        public double X_050 { get; set; }
        public double X_010 { get; set; }
        public double X_005 { get; set; }
        public decimal TransactionAmount { get; set; }
        public string GlDebit { get; set; }
        public string GlCredit { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
