//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StdOrderCharges
    {
        public long recno { get; set; }
        public int Type { get; set; }
        public decimal Sorder_Charge { get; set; }
        public string Sorder_GlAccount { get; set; }
        public System.Guid tbl_StdOrderChargesID { get; set; }
    }
}
