//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftMobileApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerAccounts
    {
        public string productname { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNo { get; set; }
        public string CustomerName { get; set; }
        public bool Locked { get; set; }
        public string AccountRemarks { get; set; }
        public string AccountComments { get; set; }
        public System.DateTime OpenedDate { get; set; }
        public string OpenedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<decimal> minimum_bal { get; set; }
        public string glmemsav { get; set; }
        public Nullable<decimal> premature_days { get; set; }
        public string prem_code { get; set; }
        public Nullable<decimal> notice_days { get; set; }
        public string noticecode { get; set; }
        public string withcomm_code { get; set; }
        public Nullable<decimal> notice_amount { get; set; }
        public Nullable<decimal> interestrate { get; set; }
        public string Encashment_code { get; set; }
        public string StatementChargeCode { get; set; }
        public string Cheque_Comm_AcHolders { get; set; }
        public string Cheque_Comm_Non_AcHolders { get; set; }
        public string Interest_payable_Account { get; set; }
        public string Interest_expense_Account { get; set; }
        public string Entrance_fee { get; set; }
        public string AccountOpening_code { get; set; }
        public Nullable<bool> Parent_Locked { get; set; }
        public string Parent_AccountRemarks { get; set; }
        public string Parent_AccountComments { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string CustomerIdNo { get; set; }
        public Nullable<int> SigningInstructions { get; set; }
        public decimal AccountType { get; set; }
        public string EmpNumber { get; set; }
        public string EmployerCode { get; set; }
        public string Branch { get; set; }
        public Nullable<bool> Recover_sorder_To_Zero { get; set; }
        public Nullable<bool> Disallow_Teller_Transactions { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> MainSavingsType { get; set; }
        public Nullable<System.DateTime> Member_Closed { get; set; }
        public Nullable<System.DateTime> Account_Closed { get; set; }
        public string MobileNo { get; set; }
        public string MemberType { get; set; }
        public string pin_number { get; set; }
        public string act_code { get; set; }
        public System.Guid tbl_CustomerID { get; set; }
        public System.Guid tbl_CustomerAccountsID { get; set; }
    }
}
